"""The `gcc` module extension.

Builds toolchains from hermetic GCC distributions and Debian sysroots.

By building the sysroots with the same Debian-distributed packages as SONiC,
we can get closer to SONiC's build environment.

This extension defines one tag, `debian_toolchain`,
which defines a gcc and binutils toolchains for a single gcc version for a single architecture on a single distro.

It also defines an auxiliary repo, `@gcc_toolchains`, for easy toolchain installation.
"""

load(":gcc.bzl", "GCC_METADATA", "fetch_gcc", "gcc_repo_name")

_TARBALL_URL = "https://github.com/blorente/gcc-builds/releases/download/{release}/gcc-toolchain-{version}-{tarball}.tar.xz"

# The repo the toolchains are generated into.
_TOOLCHAINS_REPO = "gcc_toolchains"

_GCC_DEFS = Label("//toolchains/gcc:defs.bzl")
_BINUTILS_DEFS = Label("//toolchains/binutils:defs.bzl")

# Hardcoded versions of packages for a given debian distro.
# TODO(bazel-ready): If we ever want to update the snapshots, we may want to parameterize these versions.
#                    For now, we just assume that every trixie has the same versions for all sysroot packages.
DEBIAN_SUITES = {
    "trixie": struct(
        # Major version of the GCC Debian built this sysroot with.
        gcc_major = "14",
        # Covers libgcc-s1, libgcc-N-dev, libstdc++6 and libstdc++-N-dev.
        gcc_version = "14.2.0-19",
        # Covers libc6 and libc6-dev.
        glibc_version = "2.41-12-deb13u3",
        linux_libc_dev_version = "6.12.96-1",
    ),
}

def _sysroot_labels(suite, deb):
    """Calculate labels for each part of the sysroot.

    Args:
        suite: the Debian suite the sysroot comes from, a key of DEBIAN_SUITES.
        deb: that architecture's Debian name, e.g. `amd64`.

    Returns:
        Logical name -> the canonical label of the directory holding it. The
        logical names are the ones //toolchains/gcc/args refers to packages by.
    """
    debian = DEBIAN_SUITES[suite]

    def directory(package, version, from_suite = suite):
        return str(Label("@{}_{}-{}_{}//:directory".format(
            from_suite,
            package.replace("+", "-"),
            deb,
            version,
        )))

    return {
        "linux-libc-dev": directory(
            "linux-libc-dev",
            debian.linux_libc_dev_version,
            from_suite = suite + "-security",
        ),
        "libc6": directory("libc6", debian.glibc_version),
        "libc6-dev": directory("libc6-dev", debian.glibc_version),
        "libgcc-s1": directory("libgcc-s1", debian.gcc_version),
        "libgcc-dev": directory("libgcc-{}-dev".format(debian.gcc_major), debian.gcc_version),
        "libstdcxx": directory("libstdc++6", debian.gcc_version),
        "libstdcxx-dev": directory("libstdc++-{}-dev".format(debian.gcc_major), debian.gcc_version),
    }

_BUILD_HEADER = """# Generated by //toolchains/gcc:extensions.bzl -- do not edit.
#
# One cc toolchain and one binutils toolchain per gcc.debian_toolchain() tag in
# //:MODULE.bazel. To change any of these, edit the tag that declares them.

load({binutils_defs}, "sonic_binutils_toolchain")
load({gcc_defs}, "sonic_host_toolchain")
"""

_BUILD_TOOLCHAIN = """
sonic_host_toolchain(
    name = {cc_name},
    cpu = {cpu},
    debian_gcc_major = {debian_gcc_major},
    sysroot = {sysroot},
    target_platform = {target_platform},
    version = {version},
    visibility = ["//visibility:public"],
)

sonic_binutils_toolchain(
    name = {binutils_name},
    cpu = {cpu},
    version = {version},
    visibility = ["//visibility:public"],
)
"""

_ACCEPTED_TOOLCHAIN_KINDS = ["gcc", "binutils"]

def _toolchain_name(cpu, kind, version):
    """The name of the generated `toolchain()` target for a tag.

    Args:
        cpu: the `@platforms//cpu` value, e.g. `x86_64`.
        kind: `gcc` or `binutils`.
        version: the GCC version, e.g. `14.2.0`.

    Returns:
        The target name, e.g. `host_x86_64_gcc_14.2.0`.
    """
    if kind not in _ACCEPTED_TOOLCHAIN_KINDS:
        fail("Unknown `kind` in _toolchain_name: {kind}. Accepted kinds {accepted}".format(
            kind = kind,
            accepted = _ACCEPTED_TOOLCHAIN_KINDS,
        ))
    return "host_{cpu}_{kind}_{version}".format(cpu = cpu, kind = kind, version = version)

def _gcc_toolchains_impl(rctx):
    build = [_BUILD_HEADER.format(
        binutils_defs = repr(str(_BINUTILS_DEFS)),
        gcc_defs = repr(str(_GCC_DEFS)),
    )]

    for toolchain in json.decode(rctx.attr.toolchains):
        build.append(_BUILD_TOOLCHAIN.format(
            binutils_name = repr(_toolchain_name(toolchain["cpu"], "binutils", toolchain["version"])),
            cc_name = repr(_toolchain_name(toolchain["cpu"], "gcc", toolchain["version"])),
            cpu = repr(toolchain["cpu"]),
            debian_gcc_major = repr(toolchain["debian_gcc_major"]),
            sysroot = repr(toolchain["sysroot"]),
            target_platform = repr(toolchain["target_platform"]),
            version = repr(toolchain["version"]),
        ))

    rctx.file("BUILD.bazel", "".join(build))

_gcc_toolchains = repository_rule(
    implementation = _gcc_toolchains_impl,
    doc = "Declares the cc and binutils toolchains the debian_toolchain() tags ask for.",
    attrs = {
        "toolchains": attr.string(
            doc = "The tags as JSON: a list of objects carrying `cpu`, " +
                  "`version`, `debian_gcc_major`, `sysroot`, " +
                  "and `target_platform`. JSON because repo " +
                  "rule attrs cannot hold nested dicts.",
            mandatory = True,
        ),
    },
)

def _gcc_impl(mctx):
    # We'll have up to one tag per (GCC version, arch) pair, so use that as keys.
    toolchains = {}
    for module in mctx.modules:
        for tag in module.tags.debian_toolchain:
            if (tag.version, tag.arch) in toolchains:
                fail("gcc.debian_toolchain() declares GCC {} for {} more than once; it takes one tag per (version, architecture) pair".format(
                    tag.version,
                    tag.arch,
                ))
            toolchains[(tag.version, tag.arch)] = tag

    if not toolchains:
        fail("the gcc extension needs at least one debian_toolchain() tag")

    for (version, cpu), tag in toolchains.items():
        fetch_gcc(
            name = gcc_repo_name(cpu, version),
            integrity = tag.integrity,
            target_arch = cpu,
            urls = [_TARBALL_URL.format(
                release = tag.release,
                tarball = GCC_METADATA[cpu].tarball,
                version = version,
            )],
            version = version,
        )

    # One repo holds every toolchain, so that //:MODULE.bazel imports and
    # registers a single repo however many tags it declares.
    _gcc_toolchains(
        name = _TOOLCHAINS_REPO,
        toolchains = json.encode([
            {
                "cpu": cpu,
                "debian_gcc_major": DEBIAN_SUITES[tag.suite].gcc_major,
                "sysroot": _sysroot_labels(tag.suite, GCC_METADATA[cpu].deb),
                "target_platform": str(tag.target_platform),
                "version": version,
            }
            for (version, cpu), tag in toolchains.items()
        ]),
    )

debian_toolchain = tag_class(
    doc = "Declares one GCC version for one architecture and attaches a Debian sysroot to it, to match the SONiC build environment.",
    attrs = {
        "arch": attr.string(
            doc = "The `@platforms//cpu` this tag describes, e.g. `x86_64`.",
            mandatory = True,
            values = sorted(GCC_METADATA),
        ),
        "integrity": attr.string(
            doc = "Integrity of this architecture's GCC tarball.",
            mandatory = True,
        ),
        "release": attr.string(
            doc = "The gcc-builds release holding the tarballs, e.g. `20-08-2026`.",
            mandatory = True,
        ),
        "target_platform": attr.label(
            doc = "The constraint_value() marking the environment this " +
                  "toolchain's output is deployed to, e.g. //platforms:trixie. " +
                  "Allows differentiating this toolchain from other toolchains for Linux x86, for instance.",
            mandatory = True,
        ),
        "version": attr.string(
            doc = "The GCC version we compile with, e.g. `14.2.0`. Together " +
                  "with `arch` it identifies the tag, so declaring a second " +
                  "version for an architecture means a second tag.",
            mandatory = True,
        ),
        "suite": attr.string(
            doc = "The Debian suite whose sysroot this toolchain compiles against.",
            mandatory = True,
            values = sorted(DEBIAN_SUITES),
        ),
    },
)

gcc = module_extension(
    implementation = _gcc_impl,
    doc = "Fetches the GCC distributions and declares the toolchains built from them.",
    tag_classes = {
        "debian_toolchain": debian_toolchain,
    },
)
